services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #  allows the Backend Container to talk to the host's Docker daemon
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "58632:58632"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:58632 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
